version: '3.8'

services:
  node:
    image: node:lts
    container_name: astro-blog-v2
    # monta la cartella corrente nella home di `node`
    volumes:
      - ./:/home/node/app:cached
    working_dir: /home/node/app
    # esegui come utente `node` (UID 1000)
    user: node
    ports:
      - '4321:4321'
    stdin_open: true
    tty: true
    command: tail -f /dev/null
